/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import vistas.adminCompra.ListaComprasV;
import vistas.productoOp.ListarInactivoProdV;
import vistas.productoOp.ListarProdV;
import vistas.productoOp.registrarProdV;

/**
 *
 * @author Bugaso
 */
public class ComprasV extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProducto
     */
    public ComprasV() {
        initComponents();
    }
    private Color brillo = new Color(202,70,137);
    private Color oscuro = new Color(152,70,137);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuProvPane = new javax.swing.JPanel();
        prodInaPane = new javax.swing.JPanel();
        prodInaclab = new javax.swing.JLabel();
        listarCompraPane = new javax.swing.JPanel();
        listarCompraLab = new javax.swing.JLabel();
        modProdPane = new javax.swing.JPanel();
        modProdLab = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();
        logolabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 730));
        setMinimumSize(new java.awt.Dimension(790, 730));
        setPreferredSize(new java.awt.Dimension(790, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuProvPane.setBackground(new java.awt.Color(72, 70, 119));
        menuProvPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuProvPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prodInaPane.setBackground(new java.awt.Color(152, 70, 137));
        prodInaPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        prodInaclab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        prodInaclab.setForeground(new java.awt.Color(255, 255, 255));
        prodInaclab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prodInaclab.setText("Listar Productos Inactivos");
        prodInaclab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prodInaclabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prodInaclabMouseExited(evt);
            }
        });

        javax.swing.GroupLayout prodInaPaneLayout = new javax.swing.GroupLayout(prodInaPane);
        prodInaPane.setLayout(prodInaPaneLayout);
        prodInaPaneLayout.setHorizontalGroup(
            prodInaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prodInaclab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        prodInaPaneLayout.setVerticalGroup(
            prodInaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prodInaclab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(prodInaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 180, 30));

        listarCompraPane.setBackground(new java.awt.Color(152, 70, 137));
        listarCompraPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listarCompraLab.setBackground(new java.awt.Color(255, 255, 255));
        listarCompraLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        listarCompraLab.setForeground(new java.awt.Color(255, 255, 255));
        listarCompraLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarCompraLab.setText("Listar Compras");
        listarCompraLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarCompraLabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listarCompraLabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listarCompraLabMouseExited(evt);
            }
        });

        javax.swing.GroupLayout listarCompraPaneLayout = new javax.swing.GroupLayout(listarCompraPane);
        listarCompraPane.setLayout(listarCompraPaneLayout);
        listarCompraPaneLayout.setHorizontalGroup(
            listarCompraPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarCompraLab, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        listarCompraPaneLayout.setVerticalGroup(
            listarCompraPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarCompraLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(listarCompraPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, 30));

        modProdPane.setBackground(new java.awt.Color(152, 70, 137));
        modProdPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modProdLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        modProdLab.setForeground(new java.awt.Color(255, 255, 255));
        modProdLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modProdLab.setText("Listar Productos Activos");
        modProdLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modProdLabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modProdLabMouseExited(evt);
            }
        });

        javax.swing.GroupLayout modProdPaneLayout = new javax.swing.GroupLayout(modProdPane);
        modProdPane.setLayout(modProdPaneLayout);
        modProdPaneLayout.setHorizontalGroup(
            modProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modProdLab, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        modProdPaneLayout.setVerticalGroup(
            modProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modProdLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(modProdPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 180, 30));

        add(menuProvPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        escritorio.setMaximumSize(new java.awt.Dimension(790, 680));
        escritorio.setMinimumSize(new java.awt.Dimension(790, 680));
        escritorio.setPreferredSize(new java.awt.Dimension(790, 680));

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1602174810825.jpeg"))); // NOI18N

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(logolabel))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(logolabel))
        );

        add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void listarCompraLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarCompraLabMouseClicked
        ListaComprasV listaC = new ListaComprasV();
        listaC.setVisible(true);
        listaC.setSize(790, 670);
        
        escritorio.removeAll();
        escritorio.setLocation(0, 0);
        escritorio.add(listaC,BorderLayout.CENTER);
        
        escritorio.repaint();
        escritorio.revalidate();
        
    }//GEN-LAST:event_listarCompraLabMouseClicked

    private void listarCompraLabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarCompraLabMouseEntered
        listarCompraPane.setBackground(brillo);
    }//GEN-LAST:event_listarCompraLabMouseEntered

    private void listarCompraLabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarCompraLabMouseExited
        listarCompraPane.setBackground(oscuro);
    }//GEN-LAST:event_listarCompraLabMouseExited

    private void modProdLabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modProdLabMouseEntered
        modProdPane.setBackground(brillo);
    }//GEN-LAST:event_modProdLabMouseEntered

    private void modProdLabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modProdLabMouseExited
        modProdPane.setBackground(oscuro);
    }//GEN-LAST:event_modProdLabMouseExited

    private void prodInaclabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodInaclabMouseEntered
        prodInaPane.setBackground(brillo);
    }//GEN-LAST:event_prodInaclabMouseEntered

    private void prodInaclabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodInaclabMouseExited
       prodInaPane.setBackground(oscuro);
    }//GEN-LAST:event_prodInaclabMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel listarCompraLab;
    private javax.swing.JPanel listarCompraPane;
    private javax.swing.JLabel logolabel;
    private javax.swing.JPanel menuProvPane;
    private javax.swing.JLabel modProdLab;
    private javax.swing.JPanel modProdPane;
    private javax.swing.JPanel prodInaPane;
    private javax.swing.JLabel prodInaclab;
    // End of variables declaration//GEN-END:variables
}
