/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Bugaso
 */
public class Menú extends javax.swing.JFrame {

    /**
     * Creates new form Menú
     */
    public Menú() {
        initComponents();
    }
    private BevelBorder bord = new BevelBorder(BevelBorder.RAISED, null, null, null, Color.LIGHT_GRAY);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primalPGround = new javax.swing.JPanel();
        MenusPanel = new javax.swing.JPanel();
        regisProdPane = new javax.swing.JPanel();
        regisProdLabel = new javax.swing.JLabel();
        DetalleCompraPanel = new javax.swing.JPanel();
        DetalleCompraLabel = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(928, 768));
        setPreferredSize(new java.awt.Dimension(928, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primalPGround.setBackground(new java.awt.Color(105, 70, 137));
        primalPGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenusPanel.setBackground(new java.awt.Color(162, 70, 137));
        MenusPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.lightGray));

        javax.swing.GroupLayout MenusPanelLayout = new javax.swing.GroupLayout(MenusPanel);
        MenusPanel.setLayout(MenusPanelLayout);
        MenusPanelLayout.setHorizontalGroup(
            MenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        MenusPanelLayout.setVerticalGroup(
            MenusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        primalPGround.add(MenusPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        regisProdPane.setBackground(new java.awt.Color(162, 70, 137));

        regisProdLabel.setBackground(new java.awt.Color(162, 70, 137));
        regisProdLabel.setForeground(new java.awt.Color(204, 204, 204));
        regisProdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regisProdLabel.setText("Registrar Producto");
        regisProdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisProdLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout regisProdPaneLayout = new javax.swing.GroupLayout(regisProdPane);
        regisProdPane.setLayout(regisProdPaneLayout);
        regisProdPaneLayout.setHorizontalGroup(
            regisProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regisProdPaneLayout.createSequentialGroup()
                .addComponent(regisProdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        regisProdPaneLayout.setVerticalGroup(
            regisProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regisProdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        primalPGround.add(regisProdPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 50));

        DetalleCompraPanel.setBackground(new java.awt.Color(162, 70, 137));

        DetalleCompraLabel.setBackground(new java.awt.Color(162, 70, 137));
        DetalleCompraLabel.setForeground(new java.awt.Color(204, 204, 204));
        DetalleCompraLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DetalleCompraLabel.setText("Detalle de la Compra");
        DetalleCompraLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetalleCompraLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DetalleCompraPanelLayout = new javax.swing.GroupLayout(DetalleCompraPanel);
        DetalleCompraPanel.setLayout(DetalleCompraPanelLayout);
        DetalleCompraPanelLayout.setHorizontalGroup(
            DetalleCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetalleCompraPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DetalleCompraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DetalleCompraPanelLayout.setVerticalGroup(
            DetalleCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DetalleCompraLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        primalPGround.add(DetalleCompraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 140, 50));

        escritorio.setPreferredSize(new java.awt.Dimension(800, 730));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        primalPGround.add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 810, -1));

        getContentPane().add(primalPGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DetalleCompraLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetalleCompraLabelMouseClicked
        DetalleCompraV detaC = new DetalleCompraV();
        detaC.setSize(800, 730);
        
        DetalleCompraPanel.setBorder(bord);
        MenusPanel.setBorder(null);
        regisProdPane.setBorder(null);
        escritorio.removeAll();
        escritorio.setLocation(0, 0);
        escritorio.add(detaC, BorderLayout.CENTER);
        escritorio.revalidate();
        escritorio.repaint();
    }//GEN-LAST:event_DetalleCompraLabelMouseClicked

    private void regisProdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regisProdLabelMouseClicked
        // TODO add your handling code here:
        RegistrarProducto regProd = new RegistrarProducto();
        regProd.setSize(800, 730);
        regisProdPane.setBorder(bord);
        MenusPanel.setBorder(null);
        DetalleCompraPanel.setBorder(null);
        escritorio.removeAll();
        escritorio.setLocation(0, 0);
        escritorio.add(regProd, BorderLayout.CENTER);
        escritorio.revalidate();
        escritorio.repaint();
    }//GEN-LAST:event_regisProdLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menú().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetalleCompraLabel;
    private javax.swing.JPanel DetalleCompraPanel;
    private javax.swing.JPanel MenusPanel;
    private javax.swing.JPanel escritorio;
    private javax.swing.JPanel primalPGround;
    private javax.swing.JLabel regisProdLabel;
    private javax.swing.JPanel regisProdPane;
    // End of variables declaration//GEN-END:variables
}
