/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author Bugaso
 */
public class ProductoV extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProducto
     */
    public ProductoV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuProvPane = new javax.swing.JPanel();
        elimProvePane = new javax.swing.JPanel();
        elimProdLab = new javax.swing.JLabel();
        regisProvePane = new javax.swing.JPanel();
        regisProdLab = new javax.swing.JLabel();
        modProvePane = new javax.swing.JPanel();
        modProdLab = new javax.swing.JLabel();
        buscarProvePane = new javax.swing.JPanel();
        buscProdLab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logolabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 730));
        setMinimumSize(new java.awt.Dimension(790, 730));
        setPreferredSize(new java.awt.Dimension(790, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuProvPane.setBackground(new java.awt.Color(72, 70, 119));
        menuProvPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuProvPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        elimProvePane.setBackground(new java.awt.Color(152, 70, 137));
        elimProvePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        elimProdLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        elimProdLab.setForeground(new java.awt.Color(255, 255, 255));
        elimProdLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elimProdLab.setText("Eliminar Producto");
        elimProdLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elimProdLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout elimProvePaneLayout = new javax.swing.GroupLayout(elimProvePane);
        elimProvePane.setLayout(elimProvePaneLayout);
        elimProvePaneLayout.setHorizontalGroup(
            elimProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elimProdLab, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        elimProvePaneLayout.setVerticalGroup(
            elimProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elimProdLab, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(elimProvePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 150, 30));

        regisProvePane.setBackground(new java.awt.Color(152, 70, 137));
        regisProvePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        regisProdLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        regisProdLab.setForeground(new java.awt.Color(255, 255, 255));
        regisProdLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regisProdLab.setText("Registrar Producto");
        regisProdLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisProdLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout regisProvePaneLayout = new javax.swing.GroupLayout(regisProvePane);
        regisProvePane.setLayout(regisProvePaneLayout);
        regisProvePaneLayout.setHorizontalGroup(
            regisProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regisProdLab, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        regisProvePaneLayout.setVerticalGroup(
            regisProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regisProdLab, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(regisProvePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 30));

        modProvePane.setBackground(new java.awt.Color(152, 70, 137));
        modProvePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modProdLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        modProdLab.setForeground(new java.awt.Color(255, 255, 255));
        modProdLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modProdLab.setText("Modificar Producto");
        modProdLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modProdLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout modProvePaneLayout = new javax.swing.GroupLayout(modProvePane);
        modProvePane.setLayout(modProvePaneLayout);
        modProvePaneLayout.setHorizontalGroup(
            modProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modProdLab, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        modProvePaneLayout.setVerticalGroup(
            modProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modProdLab, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(modProvePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 30));

        buscarProvePane.setBackground(new java.awt.Color(152, 70, 137));
        buscarProvePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buscProdLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        buscProdLab.setForeground(new java.awt.Color(255, 255, 255));
        buscProdLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscProdLab.setText("Buscar Producto");
        buscProdLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscProdLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buscarProvePaneLayout = new javax.swing.GroupLayout(buscarProvePane);
        buscarProvePane.setLayout(buscarProvePaneLayout);
        buscarProvePaneLayout.setHorizontalGroup(
            buscarProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscProdLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        buscarProvePaneLayout.setVerticalGroup(
            buscarProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarProvePaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buscProdLab, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuProvPane.add(buscarProvePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 170, 30));

        add(menuProvPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1602174810825.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logolabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logolabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void elimProdLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimProdLabMouseClicked
        
    }//GEN-LAST:event_elimProdLabMouseClicked

    private void regisProdLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regisProdLabMouseClicked
        
    }//GEN-LAST:event_regisProdLabMouseClicked

    private void modProdLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modProdLabMouseClicked
        
    }//GEN-LAST:event_modProdLabMouseClicked

    private void buscProdLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscProdLabMouseClicked
       
    }//GEN-LAST:event_buscProdLabMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscProdLab;
    private javax.swing.JPanel buscarProvePane;
    private javax.swing.JLabel elimProdLab;
    private javax.swing.JPanel elimProvePane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logolabel;
    private javax.swing.JPanel menuProvPane;
    private javax.swing.JLabel modProdLab;
    private javax.swing.JPanel modProvePane;
    private javax.swing.JLabel regisProdLab;
    private javax.swing.JPanel regisProvePane;
    // End of variables declaration//GEN-END:variables
}
