/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author Bugaso
 */
public class ProveedorV extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarProveedor
     */
    public ProveedorV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuProvPane = new javax.swing.JPanel();
        elimProvePane = new javax.swing.JPanel();
        elimProveLab = new javax.swing.JLabel();
        regisProvePane = new javax.swing.JPanel();
        regisProveLab = new javax.swing.JLabel();
        modProvePane = new javax.swing.JPanel();
        modProveLabe = new javax.swing.JLabel();
        buscarProvePane = new javax.swing.JPanel();
        regProvLab = new javax.swing.JLabel();
        elimProvePane1 = new javax.swing.JPanel();
        logolabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 730));
        setMinimumSize(new java.awt.Dimension(790, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuProvPane.setBackground(new java.awt.Color(72, 70, 119));
        menuProvPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuProvPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        elimProvePane.setBackground(new java.awt.Color(152, 70, 137));
        elimProvePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        elimProveLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        elimProveLab.setForeground(new java.awt.Color(255, 255, 255));
        elimProveLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elimProveLab.setText("Eliminar Proveedor");

        javax.swing.GroupLayout elimProvePaneLayout = new javax.swing.GroupLayout(elimProvePane);
        elimProvePane.setLayout(elimProvePaneLayout);
        elimProvePaneLayout.setHorizontalGroup(
            elimProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elimProveLab, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        elimProvePaneLayout.setVerticalGroup(
            elimProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elimProveLab, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(elimProvePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 150, 30));

        regisProvePane.setBackground(new java.awt.Color(152, 70, 137));
        regisProvePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        regisProveLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        regisProveLab.setForeground(new java.awt.Color(255, 255, 255));
        regisProveLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regisProveLab.setText("Registar Proveedor");

        javax.swing.GroupLayout regisProvePaneLayout = new javax.swing.GroupLayout(regisProvePane);
        regisProvePane.setLayout(regisProvePaneLayout);
        regisProvePaneLayout.setHorizontalGroup(
            regisProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regisProveLab, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        regisProvePaneLayout.setVerticalGroup(
            regisProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regisProveLab, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(regisProvePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 30));

        modProvePane.setBackground(new java.awt.Color(152, 70, 137));
        modProvePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modProveLabe.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        modProveLabe.setForeground(new java.awt.Color(255, 255, 255));
        modProveLabe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modProveLabe.setText("Modificar Proveedor");

        javax.swing.GroupLayout modProvePaneLayout = new javax.swing.GroupLayout(modProvePane);
        modProvePane.setLayout(modProvePaneLayout);
        modProvePaneLayout.setHorizontalGroup(
            modProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modProveLabe, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        modProvePaneLayout.setVerticalGroup(
            modProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modProveLabe, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        menuProvPane.add(modProvePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 30));

        buscarProvePane.setBackground(new java.awt.Color(152, 70, 137));
        buscarProvePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        regProvLab.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        regProvLab.setForeground(new java.awt.Color(255, 255, 255));
        regProvLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regProvLab.setText("Buscar Proveedor");

        javax.swing.GroupLayout buscarProvePaneLayout = new javax.swing.GroupLayout(buscarProvePane);
        buscarProvePane.setLayout(buscarProvePaneLayout);
        buscarProvePaneLayout.setHorizontalGroup(
            buscarProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regProvLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        buscarProvePaneLayout.setVerticalGroup(
            buscarProvePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarProvePaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regProvLab, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuProvPane.add(buscarProvePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 170, 30));

        add(menuProvPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        javax.swing.GroupLayout elimProvePane1Layout = new javax.swing.GroupLayout(elimProvePane1);
        elimProvePane1.setLayout(elimProvePane1Layout);
        elimProvePane1Layout.setHorizontalGroup(
            elimProvePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        elimProvePane1Layout.setVerticalGroup(
            elimProvePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(elimProvePane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 30));

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1602174810825.jpeg"))); // NOI18N
        add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buscarProvePane;
    private javax.swing.JLabel elimProveLab;
    private javax.swing.JPanel elimProvePane;
    private javax.swing.JPanel elimProvePane1;
    private javax.swing.JLabel logolabel;
    private javax.swing.JPanel menuProvPane;
    private javax.swing.JLabel modProveLabe;
    private javax.swing.JPanel modProvePane;
    private javax.swing.JLabel regProvLab;
    private javax.swing.JLabel regisProveLab;
    private javax.swing.JPanel regisProvePane;
    // End of variables declaration//GEN-END:variables
}
