/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.adminVenta;

import vistas.productoOp.*;
import accesoADatos.CompraData;
import accesoADatos.DetalleCompraData;
import accesoADatos.ProductoData;
import accesoADatos.ProveedorData;
import entidades.Compra;
import entidades.DetalleCompra;
import entidades.Producto;
import entidades.Proveedor;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import vistas.proveedorOp.DocumentSizeFilter;



/**
 *
 * @author balta
 */
public class ListarProdProvV extends javax.swing.JPanel {

    /**
     * Creates new form ListarProdV
     */
    public ListarProdProvV() {
        initComponents();
        cargarP();
        
    }
    
    private ProductoData proD = new ProductoData();

    public void cargarP(){
        ArrayList<Producto> prod = proD.listarProductos();
        
        DefaultTableModel def = (DefaultTableModel) prodtable.getModel();
        
        for(int i = def.getRowCount()-1;i>=0; i--){
            def.removeRow(i);
        } 
        for(Producto producto : prod){
            def.addRow(new Object[] {producto.getIdProducto(),producto.getNombreProducto(),producto.getDescripcion(), producto.getPrecioActual(),producto.getStock(),0});
        }
    }
    
    private void realizarCompraAngelo(){
        boolean b1 = false;
        
        if(prodtable.getSelectedRow() > -1){
            try {
                int[] filasSelec = prodtable.getSelectedRows();
                for(int i=0; i<filasSelec.length; i++){
                    int stock = (int)prodtable.getValueAt(filasSelec[i], 4);
                    int cant = (int)prodtable.getValueAt(filasSelec[i], 5);

                    if(cant > 0 && stock >= cant){
                        
                        Producto producto = proD.buscarProducto((int)prodtable.getValueAt(filasSelec[i], 0));

                        producto.setStock(stock - cant);
                        proD.modificarProducto(producto);
                        b1 = true;
                    }else{
                        b1 = false;
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "En la columna Cantidad solo debe colocar números positivos sin punto ni coma");
            }
        }else{
            b1 = false;
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un producto para vender");
        }
        
        if(b1){
            JOptionPane.showMessageDialog(this, "Venta realizada con exito");
        }
        cargarP();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        prodtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        logolabel = new javax.swing.JLabel();
        ventapane = new javax.swing.JPanel();
        ventalabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(790, 680));
        setMinimumSize(new java.awt.Dimension(790, 680));
        setPreferredSize(new java.awt.Dimension(790, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prodtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProducto", "Nombre", "Descripcion", "Precio Actual", "Stock", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prodtable.getTableHeader().setResizingAllowed(false);
        prodtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(prodtable);
        if (prodtable.getColumnModel().getColumnCount() > 0) {
            prodtable.getColumnModel().getColumn(0).setResizable(false);
            prodtable.getColumnModel().getColumn(1).setResizable(false);
            prodtable.getColumnModel().getColumn(2).setResizable(false);
            prodtable.getColumnModel().getColumn(3).setResizable(false);
            prodtable.getColumnModel().getColumn(4).setResizable(false);
            prodtable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 770, 210));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Productos para Vender");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1602174810825.jpeg"))); // NOI18N
        add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        ventapane.setBackground(new java.awt.Color(0, 102, 102));
        ventapane.setPreferredSize(new java.awt.Dimension(110, 30));

        ventalabel.setForeground(new java.awt.Color(255, 255, 255));
        ventalabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventalabel.setText("Vender");
        ventalabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventalabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ventapaneLayout = new javax.swing.GroupLayout(ventapane);
        ventapane.setLayout(ventapaneLayout);
        ventapaneLayout.setHorizontalGroup(
            ventapaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventapaneLayout.createSequentialGroup()
                .addComponent(ventalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ventapaneLayout.setVerticalGroup(
            ventapaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventapaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ventalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(ventapane, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ventalabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventalabelMouseClicked
        realizarCompraAngelo();
    }//GEN-LAST:event_ventalabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logolabel;
    private javax.swing.JTable prodtable;
    private javax.swing.JLabel ventalabel;
    private javax.swing.JPanel ventapane;
    // End of variables declaration//GEN-END:variables
}
