/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.proveedorOp;

/**
 *
 * @author Bugaso
 */
public class modificarProveV extends javax.swing.JPanel {

    /**
     * Creates new form modificarProveV
     */
    public modificarProveV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscuitlabel = new javax.swing.JLabel();
        buscarcuit = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 680));
        setMinimumSize(new java.awt.Dimension(790, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Proveedores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        buscuitlabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        buscuitlabel.setForeground(new java.awt.Color(0, 0, 0));
        buscuitlabel.setText("Ingrese el cuit:");
        add(buscuitlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        buscarcuit.setBackground(new java.awt.Color(255, 255, 255));
        buscarcuit.setForeground(java.awt.Color.lightGray);
        buscarcuit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        buscarcuit.setText("Cuit");
        buscarcuit.setBorder(null);
        add(buscarcuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 230, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 230, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Razon social/Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(null);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 230, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 172, 230, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarcuit;
    private javax.swing.JLabel buscuitlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
