/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.adminCompra;

import accesoADatos.CompraData;
import accesoADatos.DetalleCompraData;
import accesoADatos.ProductoData;
import entidades.Compra;
import entidades.DetalleCompra;
import entidades.Producto;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author balta
 */
public class ListaComprasV extends javax.swing.JPanel {

    /**
     * Creates new form ListaComprasV
     */
    public ListaComprasV() {
        initComponents();
        CargarC();
        compraTab.setRowSelectionAllowed(true);
	compraTab.setColumnSelectionAllowed(false);
        compraTab.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    ProductoData proD = new ProductoData();
    private CompraData compraD = new CompraData();
    private DetalleCompraData detaD = new DetalleCompraData();
    
    public void LimpiarDetaT(){
         DefaultTableModel def = (DefaultTableModel) detalleTab.getModel();
        
        for(int i = def.getRowCount()-1;i>=0; i--){
            def.removeRow(i);
        }
    }
    
    public void CargarC(){
        ArrayList<Compra> compraL = compraD.listarCompras();
        
        DefaultTableModel def = (DefaultTableModel) compraTab.getModel();
        
        for(int i = def.getRowCount()-1;i>=0; i--){
            def.removeRow(i);
        }
        for(Compra compra : compraL){
            def.addRow(new Object[] {compra.getIdCompra(),compra.getProveedor().getIdProveedor(),compra.getProveedor().getRazonSocial(),compra.getFecha()});
        }
    }
    
    public void CargarCF (LocalDate fecha){
        ArrayList<DetalleCompra> compraL = detaD.productosDeUnaCompraDeUnaFecha(fecha);
        
        DefaultTableModel def = (DefaultTableModel) compraTab.getModel();
        
        for(int i = def.getRowCount()-1;i>=0; i--){
            def.removeRow(i);
        }
        for(DetalleCompra compra : compraL){
            def.addRow(new Object[] {compra.getCompra().getIdCompra(),compra.getCompra().getProveedor().getIdProveedor(),compra.getCompra().getProveedor().getRazonSocial(),compra.getCompra().getFecha()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logolabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        compraTab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listarFecha = new com.toedter.calendar.JDateChooser();
        listarPane = new javax.swing.JPanel();
        listarLab = new javax.swing.JLabel();
        mostrarPane = new javax.swing.JPanel();
        mostrarLab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detalleTab = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(790, 680));
        setMinimumSize(new java.awt.Dimension(790, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1602174810825.jpeg"))); // NOI18N
        add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 110));

        compraTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idCompra", "idProveedor", "Razon Social", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        compraTab.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(compraTab);
        if (compraTab.getColumnModel().getColumnCount() > 0) {
            compraTab.getColumnModel().getColumn(0).setResizable(false);
            compraTab.getColumnModel().getColumn(0).setPreferredWidth(10);
            compraTab.getColumnModel().getColumn(1).setResizable(false);
            compraTab.getColumnModel().getColumn(1).setPreferredWidth(10);
            compraTab.getColumnModel().getColumn(2).setResizable(false);
            compraTab.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 430, 310));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Compras");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Listar por fecha:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        add(listarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, -1));

        listarPane.setBackground(new java.awt.Color(102, 0, 102));

        listarLab.setForeground(new java.awt.Color(255, 255, 255));
        listarLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarLab.setText("Listar Compras");
        listarLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout listarPaneLayout = new javax.swing.GroupLayout(listarPane);
        listarPane.setLayout(listarPaneLayout);
        listarPaneLayout.setHorizontalGroup(
            listarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        listarPaneLayout.setVerticalGroup(
            listarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(listarPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, 40));

        mostrarPane.setBackground(new java.awt.Color(0, 102, 102));

        mostrarLab.setForeground(new java.awt.Color(255, 255, 255));
        mostrarLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarLab.setText("Mostrar Detalle");
        mostrarLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mostrarPaneLayout = new javax.swing.GroupLayout(mostrarPane);
        mostrarPane.setLayout(mostrarPaneLayout);
        mostrarPaneLayout.setHorizontalGroup(
            mostrarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarPaneLayout.createSequentialGroup()
                .addComponent(mostrarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mostrarPaneLayout.setVerticalGroup(
            mostrarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostrarPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mostrarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(mostrarPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 130, 30));

        detalleTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Descripcion", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        detalleTab.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(detalleTab);
        if (detalleTab.getColumnModel().getColumnCount() > 0) {
            detalleTab.getColumnModel().getColumn(0).setResizable(false);
            detalleTab.getColumnModel().getColumn(1).setResizable(false);
            detalleTab.getColumnModel().getColumn(2).setResizable(false);
            detalleTab.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 310, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void listarLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarLabMouseClicked
        LocalDate fecha = listarFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        CargarCF(fecha);
    }//GEN-LAST:event_listarLabMouseClicked

    private void mostrarLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarLabMouseClicked
        
        DefaultTableModel tableM = (DefaultTableModel) detalleTab.getModel();
        ArrayList<DetalleCompra> prodL = detaD.productosDeUnaCompra((int) compraTab.getValueAt(compraTab.getSelectedRow(), 0));
        
        LimpiarDetaT();
        
        
        for(DetalleCompra prod : prodL){
           tableM.addRow(new Object[] {prod.getProducto().getNombreProducto(),prod.getProducto().getDescripcion(),prod.getProducto().getPrecioActual(),prod.getCantidad()});
        }

    }//GEN-LAST:event_mostrarLabMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable compraTab;
    private javax.swing.JTable detalleTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser listarFecha;
    private javax.swing.JLabel listarLab;
    private javax.swing.JPanel listarPane;
    private javax.swing.JLabel logolabel;
    private javax.swing.JLabel mostrarLab;
    private javax.swing.JPanel mostrarPane;
    // End of variables declaration//GEN-END:variables
}
