/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.adminCompra;

import accesoADatos.CompraData;
import accesoADatos.DetalleCompraData;
import accesoADatos.ProductoData;
import entidades.Compra;
import entidades.DetalleCompra;
import entidades.Producto;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author balta
 */
public class ListaComprasV extends javax.swing.JPanel {

    /**
     * Creates new form ListaComprasV
     */
    public ListaComprasV() {
        initComponents();
        CargarC();
    }
    ProductoData proD = new ProductoData();
    private CompraData compraD = new CompraData();
    private DetalleCompraData detaD = new DetalleCompraData();
    public void CargarC(){
        ArrayList<Compra> compraL = compraD.listarCompras();
        
        DefaultTableModel def = (DefaultTableModel) compraTab.getModel();
        
        for(int i = def.getRowCount()-1;i>=0; i--){
            def.removeRow(i);
        }
        for(Compra compra : compraL){
            def.addRow(new Object[] {compra.getIdCompra(),compra.getProveedor().getIdProveedor(),compra.getProveedor().getRazonSocial(),compra.getFecha()});
        }
    }
    
    public void CargarCF (LocalDate fecha){
        ArrayList<DetalleCompra> compraL = detaD.productosDeUnaCompraDeUnaFecha(fecha);
        
        DefaultTableModel def = (DefaultTableModel) compraTab.getModel();
        
        for(int i = def.getRowCount()-1;i>=0; i--){
            def.removeRow(i);
        }
        for(DetalleCompra compra : compraL){
            def.addRow(new Object[] {compra.getCompra().getIdCompra(),compra.getCompra().getProveedor().getIdProveedor(),compra.getCompra().getProveedor().getRazonSocial(),compra.getCompra().getFecha()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logolabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        compraTab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listarFecha = new com.toedter.calendar.JDateChooser();
        listarPane = new javax.swing.JPanel();
        listarLab = new javax.swing.JLabel();
        mostrarPane = new javax.swing.JPanel();
        mostrarLab = new javax.swing.JLabel();
        eliminarpan = new javax.swing.JPanel();
        eliminarlabel = new javax.swing.JLabel();
        limpiarPane = new javax.swing.JPanel();
        limpiarLab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detalleCompra = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(790, 680));
        setMinimumSize(new java.awt.Dimension(790, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1602174810825.jpeg"))); // NOI18N
        add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 110));

        compraTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idCompra", "idProveedor", "Razon Social", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        compraTab.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(compraTab);
        if (compraTab.getColumnModel().getColumnCount() > 0) {
            compraTab.getColumnModel().getColumn(0).setResizable(false);
            compraTab.getColumnModel().getColumn(0).setPreferredWidth(10);
            compraTab.getColumnModel().getColumn(1).setResizable(false);
            compraTab.getColumnModel().getColumn(1).setPreferredWidth(10);
            compraTab.getColumnModel().getColumn(2).setResizable(false);
            compraTab.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 430, 310));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Compras");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Listar por fecha:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        add(listarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, -1));

        listarPane.setBackground(new java.awt.Color(102, 0, 102));

        listarLab.setForeground(new java.awt.Color(255, 255, 255));
        listarLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarLab.setText("Listar Compras");
        listarLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout listarPaneLayout = new javax.swing.GroupLayout(listarPane);
        listarPane.setLayout(listarPaneLayout);
        listarPaneLayout.setHorizontalGroup(
            listarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        listarPaneLayout.setVerticalGroup(
            listarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(listarPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, 40));

        mostrarPane.setBackground(new java.awt.Color(0, 102, 102));

        mostrarLab.setForeground(new java.awt.Color(255, 255, 255));
        mostrarLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarLab.setText("Mostrar Detalle");
        mostrarLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarLabMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mostrarPaneLayout = new javax.swing.GroupLayout(mostrarPane);
        mostrarPane.setLayout(mostrarPaneLayout);
        mostrarPaneLayout.setHorizontalGroup(
            mostrarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarLab, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        mostrarPaneLayout.setVerticalGroup(
            mostrarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarLab, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(mostrarPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, 30));

        eliminarpan.setBackground(new java.awt.Color(102, 0, 0));

        eliminarlabel.setForeground(new java.awt.Color(255, 255, 255));
        eliminarlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminarlabel.setText("Eliminar Compra");
        eliminarlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout eliminarpanLayout = new javax.swing.GroupLayout(eliminarpan);
        eliminarpan.setLayout(eliminarpanLayout);
        eliminarpanLayout.setHorizontalGroup(
            eliminarpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarpanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(eliminarlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        eliminarpanLayout.setVerticalGroup(
            eliminarpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarpanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(eliminarlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(eliminarpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 120, 30));

        limpiarPane.setBackground(new java.awt.Color(0, 0, 51));

        limpiarLab.setForeground(new java.awt.Color(255, 255, 255));
        limpiarLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limpiarLab.setText("Limpiar campos");

        javax.swing.GroupLayout limpiarPaneLayout = new javax.swing.GroupLayout(limpiarPane);
        limpiarPane.setLayout(limpiarPaneLayout);
        limpiarPaneLayout.setHorizontalGroup(
            limpiarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limpiarLab, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        limpiarPaneLayout.setVerticalGroup(
            limpiarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(limpiarLab, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(limpiarPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Detalle de Compra Seleccionada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 240, 30));

        detalleCompra.setToolTipText("");
        jScrollPane3.setViewportView(detalleCompra);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 240, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarlabelMouseClicked
        
    }//GEN-LAST:event_eliminarlabelMouseClicked

    private void listarLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarLabMouseClicked
        LocalDate fecha = listarFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        CargarCF(fecha);
    }//GEN-LAST:event_listarLabMouseClicked

    private void mostrarLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarLabMouseClicked
        DefaultListModel<String> listModel = (DefaultListModel<String>) detalleCompra.getModel();
        
        
    }//GEN-LAST:event_mostrarLabMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable compraTab;
    private javax.swing.JList<String> detalleCompra;
    private javax.swing.JLabel eliminarlabel;
    private javax.swing.JPanel eliminarpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel limpiarLab;
    private javax.swing.JPanel limpiarPane;
    private com.toedter.calendar.JDateChooser listarFecha;
    private javax.swing.JLabel listarLab;
    private javax.swing.JPanel listarPane;
    private javax.swing.JLabel logolabel;
    private javax.swing.JLabel mostrarLab;
    private javax.swing.JPanel mostrarPane;
    // End of variables declaration//GEN-END:variables
}
