/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.adminCompra;

/**
 *
 * @author balta
 */
public class registrarCompraV extends javax.swing.JPanel {

    /**
     * Creates new form registrarCompraV
     */
    public registrarCompraV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        comboprove = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cuittext = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        comboprod = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        idtext = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(790, 680));
        setMinimumSize(new java.awt.Dimension(790, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Registro de Compra");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        comboprove.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuit / Razon social" }));
        add(comboprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 140, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Seleccione Proveedor:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 20));

        cuittext.setForeground(java.awt.Color.lightGray);
        cuittext.setText("Cuit");
        cuittext.setBorder(null);
        add(cuittext, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 100, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 100, 10));

        comboprod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuit / Razon social" }));
        add(comboprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 140, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText(" Seleccione Producto:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 20));

        idtext.setForeground(java.awt.Color.lightGray);
        idtext.setText("Cuit");
        idtext.setBorder(null);
        add(idtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 100, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 100, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboprod;
    private javax.swing.JComboBox<String> comboprove;
    private javax.swing.JTextField cuittext;
    private javax.swing.JTextField idtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
