/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.adminProvProd;

/**
 *
 * @author compu
 */
public class productoProveV extends javax.swing.JPanel {

    /**
     * Creates new form productoProveV
     */
    public productoProveV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechatext = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        detalleCompraTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        NumCtext = new javax.swing.JTextField();
        logolabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalptext = new javax.swing.JTextField();
        PaneGuardar = new javax.swing.JPanel();
        jLGuardar = new javax.swing.JLabel();
        Panecance = new javax.swing.JPanel();
        jLCancelar = new javax.swing.JLabel();
        PaneMod = new javax.swing.JPanel();
        jLModificar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 680));
        setMinimumSize(new java.awt.Dimension(790, 680));
        setPreferredSize(new java.awt.Dimension(790, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Productos del Proveedor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 330, 33));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, 20));

        fechatext.setBackground(new java.awt.Color(255, 255, 255));
        fechatext.setBorder(null);
        add(fechatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 164, 208, -1));

        detalleCompraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Descripcion", "PrecioUnitario", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detalleCompraTable.getTableHeader().setResizingAllowed(false);
        detalleCompraTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(detalleCompraTable);
        if (detalleCompraTable.getColumnModel().getColumnCount() > 0) {
            detalleCompraTable.getColumnModel().getColumn(0).setResizable(false);
            detalleCompraTable.getColumnModel().getColumn(1).setResizable(false);
            detalleCompraTable.getColumnModel().getColumn(2).setResizable(false);
            detalleCompraTable.getColumnModel().getColumn(3).setResizable(false);
            detalleCompraTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 209, 705, 110));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nº cliente:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 20));

        NumCtext.setBackground(new java.awt.Color(255, 255, 255));
        NumCtext.setBorder(null);
        add(NumCtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 164, 208, -1));

        logolabel.setFont(new java.awt.Font("Dialog", 0, 3)); // NOI18N
        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1602174810825.jpeg"))); // NOI18N
        logolabel.setMaximumSize(new java.awt.Dimension(790, 730));
        logolabel.setMinimumSize(new java.awt.Dimension(790, 730));
        logolabel.setPreferredSize(new java.awt.Dimension(790, 730));
        add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 194, 93));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Total de los productos seleccionados:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        totalptext.setBackground(new java.awt.Color(255, 255, 255));
        totalptext.setBorder(null);
        add(totalptext, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 330, 130, 20));

        PaneGuardar.setBackground(new java.awt.Color(0, 153, 0));

        jLGuardar.setBackground(new java.awt.Color(0, 102, 102));
        jLGuardar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jLGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLGuardar.setText("Guardar");
        jLGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PaneGuardarLayout = new javax.swing.GroupLayout(PaneGuardar);
        PaneGuardar.setLayout(PaneGuardarLayout);
        PaneGuardarLayout.setHorizontalGroup(
            PaneGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        PaneGuardarLayout.setVerticalGroup(
            PaneGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(PaneGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 100, 40));

        Panecance.setBackground(new java.awt.Color(102, 0, 0));

        jLCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jLCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCancelar.setText("Cancelar");

        javax.swing.GroupLayout PanecanceLayout = new javax.swing.GroupLayout(Panecance);
        Panecance.setLayout(PanecanceLayout);
        PanecanceLayout.setHorizontalGroup(
            PanecanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        PanecanceLayout.setVerticalGroup(
            PanecanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(Panecance, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 110, 40));

        PaneMod.setBackground(new java.awt.Color(0, 102, 153));

        jLModificar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLModificar.setForeground(new java.awt.Color(0, 0, 0));
        jLModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLModificar.setText("Modificar");

        javax.swing.GroupLayout PaneModLayout = new javax.swing.GroupLayout(PaneMod);
        PaneMod.setLayout(PaneModLayout);
        PaneModLayout.setHorizontalGroup(
            PaneModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneModLayout.createSequentialGroup()
                .addComponent(jLModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PaneModLayout.setVerticalGroup(
            PaneModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneModLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(PaneMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 100, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 210, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 210, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 130, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jLGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLGuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLGuardarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumCtext;
    private javax.swing.JPanel PaneGuardar;
    private javax.swing.JPanel PaneMod;
    private javax.swing.JPanel Panecance;
    private javax.swing.JTable detalleCompraTable;
    private javax.swing.JTextField fechatext;
    private javax.swing.JLabel jLCancelar;
    private javax.swing.JLabel jLGuardar;
    private javax.swing.JLabel jLModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logolabel;
    private javax.swing.JTextField totalptext;
    // End of variables declaration//GEN-END:variables
}
