/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.productoOp;

import accesoADatos.CompraData;
import accesoADatos.DetalleCompraData;
import accesoADatos.ProductoData;
import accesoADatos.ProveedorData;
import entidades.Compra;
import entidades.DetalleCompra;
import entidades.Producto;
import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author compu
 */
public class ListarInactivoProdV extends javax.swing.JPanel {

    /**
     * Creates new form ListarInactivoProdV
     */
    public ListarInactivoProdV() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        provbox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodtable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comprarlabel = new javax.swing.JLabel();
        idtext = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(790, 680));
        setMinimumSize(new java.awt.Dimension(790, 680));
        setPreferredSize(new java.awt.Dimension(790, 680));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Productos Inactivos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 65, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Buscar Proveedor:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 208, 194, -1));

        provbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuit / Razon social" }));
        provbox.setBorder(null);
        provbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provboxActionPerformed(evt);
            }
        });
        add(provbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 210, 30));

        prodtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProducto", "Nombre", "Descripcion", "Precio Actual", "Stock", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prodtable.getTableHeader().setResizingAllowed(false);
        prodtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(prodtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 770, 132));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, 40));

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setMinimumSize(new java.awt.Dimension(110, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, 30));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));
        jPanel4.setMinimumSize(new java.awt.Dimension(110, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Refrescar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setMinimumSize(new java.awt.Dimension(110, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, 30));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Buscar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 110, 30));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setMinimumSize(new java.awt.Dimension(110, 30));
        jPanel7.setPreferredSize(new java.awt.Dimension(41, 14));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Alta");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 110, 30));

        comprarlabel.setForeground(new java.awt.Color(255, 255, 255));
        comprarlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comprarlabel.setText("Comprar");
        comprarlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprarlabelMouseClicked(evt);
            }
        });
        add(comprarlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        idtext.setText("Ingrese cuit del Proveedor");
        idtext.setBorder(null);
        add(idtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void provboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provboxActionPerformed
        String cuit = "";
        try{
            for(int i= 0;i<11;i++){
                cuit+= provbox.getSelectedItem().toString().charAt(i);
            }
            idtext.setText(cuit);
            idtext.setForeground(Color.BLACK);
        }catch(NumberFormatException e){

        }
    }//GEN-LAST:event_provboxActionPerformed
    private DetalleCompraData detaCD = new DetalleCompraData();
    private CompraData compraD = new CompraData();
    private ProveedorData proveD = new ProveedorData();
    private ProductoData proD = new ProductoData(); 
    private void comprarlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprarlabelMouseClicked

        int stock = 0;
        int cant = 0;
        int[] filas;

        if(prodtable.getSelectedRowCount() >0){
            filas = prodtable.getSelectedRows();
            System.out.println("Cantidad de filas seleccionadas: "+prodtable.getSelectedRowCount());
            Compra compra[] = new Compra[prodtable.getSelectedRowCount()];
            DetalleCompra detaC = new DetalleCompra();
            Producto prod[] = new Producto [prodtable.getSelectedRowCount()];
            try{

                for (int i = 0; i<=prodtable.getSelectedRowCount();i++){
                    System.out.println("Valor de la fila: "+filas[i]);
                    cant = (int) prodtable.getValueAt(filas[i], 5);
                    stock = (int) prodtable.getValueAt(filas[i], 4);
                    if(cant > 0){
                        compra[i] = new Compra();
                        prod[i] = new Producto();
                        if( cant <= stock){
                            compra[i].setProveedor(proveD.buscarProveedorPorcuit(Long.valueOf(idtext.getText())));
                            compra[i].setFecha(LocalDate.now());
                            compraD.guardarCompra(compra[i]);
                            detaC.setCantidad((int) prodtable.getValueAt(filas[i], 4));
                            detaC.setCompra(compra[i]);
                            detaC.setPrecioCosto((double)prodtable.getValueAt(filas[i], 3));
                            prod[i] = proD.buscarProducto((int) prodtable.getValueAt(filas[i], 0));
                            detaC.setProducto(prod[i]);
                            detaCD.guardarDetalleCompra(detaC);
                            prod[i].setStock(stock-cant);
                            proD.modificarProducto(prod[i]);
                            
                        }
                    }else{
                        System.out.println("Ingrese algo en la compra");
                    }
                }

            }catch(NumberFormatException e){
                System.out.println("Esta mal");
            }
        }

    }//GEN-LAST:event_comprarlabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comprarlabel;
    private javax.swing.JTextField idtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable prodtable;
    private javax.swing.JComboBox<String> provbox;
    // End of variables declaration//GEN-END:variables
}
